version: '3.7'
services:
    proxy:
        container_name: alertifa_nginx
        image: alertifa_nginx:${VERSION}
        build: ./nginx/.
        volumes:
            - ${LETSENCRYPT}:/etc/letsencrypt:ro
            - ./logs/nginx:/var/log/nginx:rw
        ports:
            - ${NGINX_BIND_ADDRESS}:80:80
            - ${NGINX_BIND_ADDRESS}:443:443
        networks: 
            - backnet
        depends_on: 
            - app
        environment: 
            SERVER_NAME: ${SERVER_NAME}
            SSL_CERTIFICATE: ${SSL_CERTIFICATE}
            SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY}
            INCLUDE: ${INCLUDE}
            SSL_DHPARAM: ${SSL_DHPARAM}

    db:
        container_name: alertifa_postgres
        image: alertifa_postgres:${VERSION}
        build: ./database/.
        volumes:
            - ./database/pgdata:/var/lib/postgresql/data:rw
            - ./logs/database:/var/lib/postgresql/logs:rw
        networks: 
            - dbnet
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    app:
        container_name: alertifa_python
        image: alertifa_python:${VERSION}
        build: ./app/.
        volumes:
            - ./logs/app:/logs:rw
        networks: 
            - backnet
            - dbnet
        depends_on:
            - db
        environment: 
            DB_CONNECTION: ${DB_CONNECTION}
            SECRET_KEY: ${SECRET_KEY}
            ALGORITHM: ${ALGORITHM}
            AUTH_HEADER: ${AUTH_HEADER}
            AUTH_SCHEME: ${AUTH_SCHEME}
            PROJECT_NAME: ${PROJECT_NAME}
            MAX_CONNECTIONS_COUNT: ${MAX_CONNECTIONS_COUNT}
            MIN_CONNECTIONS_COUNT: ${MIN_CONNECTIONS_COUNT}
            VERSION: ${VERSION}

networks:
    backnet:
        name: backnet
    dbnet:
        name: dbnet
        ipam:
            driver: default
            config:
              - subnet: "172.16.238.0/24"