version: '3.7'
services:
    nginx:
        build: ./nginx/.
        container_name: nginx
        volumes:
            - ./nginx/letsencrypt:/etc/letsencrypt:ro
            - ./logs/nginx:/var/log/nginx:rw
        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"
            # - "80:80"
            # - "443:443"
        networks: 
            - frontend
            - backend
        depends_on: 
            - python

    postgres:
        container_name: db
        build: ./database/.
        volumes:
            - ./database/pgdata:/var/lib/postgresql/pgdata:rw
            - ./database/postgresql.conf:/var/lib/postgresql/pgdata/postgresql.conf:rw
            - ./database/pg_hba.conf:/var/lib/postgresql/pgdata/pg_hba.conf:rw
            - ./logs/database:/var/lib/postgresql/data:rw
        env_file:
            - ./database/.env
        # environment:
        #     - POSTGRES_PASSWORD=UmptKgehOxrO
        #     - PGDATA=/var/lib/postgresql/pgdata
        networks:
            - dbnet

    db_init:
        container_name: db_init
        build: ./database_init/.
        networks: 
            - dbnet
        depends_on: 
            - postgres
    db_populate:
        container_name: db_populate
        build: ./database_populate/.
        networks: 
            - dbnet
        depends_on: 
            - db_init

    python:
        container_name: app
        build: ./app/.
        env_file:
            - ./app/.env
        volumes:
            - ./logs:/logs:rw
        networks: 
            - backend
            - dbnet
        depends_on:
            # - postgres
            - db_populate

    unit_test_account:
        container_name: unit_test_account
        build: ./unit_test/account/.
        networks: 
            - frontend
            - backend
        depends_on:
            - nginx
    unit_test_permissions:
        container_name: unit_test_permissions
        build: ./unit_test/permissions/.
        networks: 
            - frontend
            - dbnet
        depends_on: 
            - unit_test_account

networks:
    frontend:
        name: frontend
    backend:
        name: backend
    dbnet:
        name: dbnet
        ipam:
            driver: default
            config:
              - subnet: "172.16.238.0/24"